DROP TABLE HT_INVOICES;
DROP TABLE HT_SERVICE_CHARGES;
DROP TABLE HT_BOOKINGS;
DROP TABLE HT_ROOMS;
DROP TABLE HT_AMENITIES;
DROP TABLE HT_ROOM_TYPES;
DROP TABLE HT_SERVICES;
DROP TABLE HT_HOTELS;
DROP TABLE HT_MEMBERS;
-- TABLE HT_MEMBERS 
CREATE TABLE HT_MEMBERS(
    MEMBER_ID INT NOT NULL,
    FIRSTNAME VARCHAR2(30) NOT NULL,
    LASTNAME VARCHAR2(30) NOT NULL,
    MEMBER_SINCE DATE NOT NULL,
    STREET_ADDRESS VARCHAR2(30) NOT NULL,
    CITY VARCHAR2(30) NOT NULL,
    STATE VARCHAR2(30) NOT NULL,
    COUNTRY VARCHAR2(30) NOT NULL,
    POSTAL_CODE VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    PRIMARY KEY(MEMBER_ID)
);

-- TABLE HT_HOTELS 
CREATE TABLE HT_HOTELS(
    HOTEL_ID INT NOT NULL,
    HOTEL_NAME VARCHAR2(30) NOT NULL,
    CITY VARCHAR2(30) NOT NULL,
    COUNTRY VARCHAR2(30) NOT NULL,
    REGION VARCHAR2(30) NOT NULL,
    PRIMARY KEY(HOTEL_ID)
);

-- TABLE HT_SERVICES 
CREATE TABLE HT_SERVICES(
    SERVICES_ID INT NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    COST INT NOT NULL,
    PRIMARY KEY(SERVICES_ID)
);

-- TABLE HT_ROOM_TYPES  
CREATE TABLE HT_ROOM_TYPES(
    ROOM_TY_ID INT NOT NULL,
    TYPE_NAME VARCHAR2(30) NOT NULL,
    PRIMARY KEY(ROOM_TY_ID)
);

-- TABLE HT_AMENITIES 
CREATE TABLE HT_AMENITIES(
    AMENITY_ID INT NOT NULL,
    HOTEL_ID INT,
    AMT_NAME VARCHAR2(30) NOT NULL,
    AMT_DESC VARCHAR2(50) NOT NULL,
    PRIMARY KEY(AMENITY_ID),
    CONSTRAINT FK_HOTEL_ID FOREIGN KEY(HOTEL_ID) REFERENCES HT_HOTELS(HOTEL_ID)
);

-- TABLE HT_ROOMS
CREATE TABLE HT_ROOMS(
    ROOM_ID INT NOT NULL,
    HOTEL_ID INT NOT NULL,
    ROOM_TY_ID INT NOT NULL,
    COST_PER_NIGHT NUMBER(5,2) NOT NULL,
    AVAILABILITY VARCHAR2(20),
    PRIMARY KEY(ROOM_ID),
    CONSTRAINT FK_HOTEL_ID_ROOMS FOREIGN KEY(HOTEL_ID) REFERENCES HT_HOTELS(HOTEL_ID),
    CONSTRAINT FK_ROOM_TY_ID_ROOMS FOREIGN KEY(ROOM_TY_ID) REFERENCES HT_ROOM_TYPES(ROOM_TY_ID)
);

-- TABLE HT_BOOKINGS
CREATE TABLE HT_BOOKINGS(
    BOOKING_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    HOTEL_ID INT NOT NULL,
    ROOM_TY_ID INT NOT NULL,
    CHECK_IN DATE NOT NULL,
    CHECK_OUT DATE NOT NULL,
    NUM_ADULTS INT NOT NULL,
    NUM_CHILDREN INT NOT NULL,
    NUM_PETS INT NOT NULL,
    PRIMARY KEY(BOOKING_ID),
    CONSTRAINT FK_MEMBER_ID_BOOKINGS FOREIGN KEY(MEMBER_ID) REFERENCES HT_MEMBERS(MEMBER_ID),
    CONSTRAINT FK_HOTEL_ID_BOOKINGS FOREIGN KEY(HOTEL_ID) REFERENCES HT_HOTELS(HOTEL_ID),
    CONSTRAINT FK_ROOM_TY_ID_BOOKINGS FOREIGN KEY(ROOM_TY_ID) REFERENCES HT_ROOM_TYPES(ROOM_TY_ID)
    
);

-- TABLE HT_SERVICE_CHARGES
CREATE TABLE HT_SERVICE_CHARGES(
    SERVICE_CHARGE_ID INT NOT NULL,
    BOOKING_ID INT NOT NULL,
    SERVICE_ID INT NOT NULL,
    PRIMARY KEY(SERVICE_CHARGE_ID),
    CONSTRAINT FK_BOOKING_ID_CHARGES FOREIGN KEY(BOOKING_ID) REFERENCES HT_BOOKINGS(BOOKING_ID),
    CONSTRAINT FK_SERVICE_ID_CHARGES FOREIGN KEY(SERVICE_ID) REFERENCES HT_SERVICES(SERVICES_ID)
);

-- TABLE HT_INVOICES
CREATE TABLE HT_INVOICES(
    INVOICE_ID INT NOT NULL,
    BOOKING_ID INT NOT NULL,
   
    IS_PAID VARCHAR2(20) NOT NULL,
    SUBTOTAL NUMBER(10,2) NOT NULL,
    TAX NUMBER(10,2) NOT NULL,
    TOTAL NUMBER(10,2) NOT NULL,
    PAYMENT_DT DATE NOT NULL,
    PRIMARY KEY(INVOICE_ID),
    CONSTRAINT FK_BOOKING_ID_INVOICES FOREIGN KEY(BOOKING_ID) REFERENCES HT_BOOKINGS(BOOKING_ID)
   
);
